Adds account number option
bvlaicu/coned pull request #10
Opened 2022-02-07 17:47 UTC by smitchsmith

It seems that you need to navigate to an account page before you are considered "logged in" and able to retrieve data. So if you have more than one service address, you'll get a page like this:

<img width="980" alt="screenshot" src="https://user-images.githubusercontent.com/5808301/152842968-27ac11f7-a169-4395-b6c1-f9dbb1c7737b.png">

This allows you to specify a page to navigate to. The account number can be pulled from the URL, ex. https://www.coned.com/en/accounts-billing/dashboard?account=XXXXXXXXXXXXXXX

2022-02-10 00:15 UTC, bvlaicu requested changes

2022-02-10 00:15 UTC, bvlaicu commented on coned/meter.py
> +            account_page_url = 'https://www.coned.com/en/accounts-billing/dashboard?account=' + self.account_number
Can you please use `self.site` instead of hardcoded `coned` here. Thanks.

2022-02-18 00:25 UTC, smitchsmith commented on coned/meter.py
> +            account_page_url = 'https://www.coned.com/en/accounts-billing/dashboard?account=' + self.account_number
thanks, should be fixed now.

2022-02-19 14:47 UTC, bvlaicu approved these changes

2022-02-19 14:48 UTC, merged